server:
  port: 8001
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
    session:
      timeout: 4h

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exhibition?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


  thymeleaf:
    cache: false
    mode: HTML

mybatis:
  type-aliases-package: com.honji.exhibition.admin


mybatis-plus:
    # 支持统配符 * 或者 ; 分割
    typeEnumsPackage: com.honji.exhibition.admin.enums
    configuration:
      default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler


logging:
  file: logs/exhibition-admin.log
  level:
    com.honji.exhibition.admin.mapper: debug
    root: INFO
