server:
  port: 8000
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
    session:
      timeout: 1h

spring:
  datasource:
    url: jdbc:mysql://10.10.10.107:3306/exhibition-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: ipos
    password: hongjipos@2016
    driver-class-name: com.mysql.jdbc.Driver


  thymeleaf:
    cache: false
    mode: HTML

mybatis:
  type-aliases-package: com.honji.exhibition


mybatis-plus:
    # 支持统配符 * 或者 ; 分割
    typeEnumsPackage: com.honji.exhibition.enums
    configuration:
      default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler


mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  not-empty: true

wx:
  mp:
    appId: wx96f9924f0c3cd767
    secret: 76245364915271d03c19f9fa638817e8
    token: wff896uy53fr54l12xd954fgkl2qsa56
    aesKey: TrggU0NiO105hc7bK7DGZVF7CACo5vyu4YPb6FCB0A9
logging:

  file: logs/exhibition.log
  level:
    com.honji.exhibition.mapper: debug
    root: INFO
